runtime: php55

handlers:
# Serve images as static resources.
- url: /(.+\.(eot|svg|ttf|woff|woff2|css|js|gif|png|jpg|xml|ico|webmanifest))$
  static_files: \1
  upload: .+\.(eot|svg|ttf|woff|woff2|css|js|gif|png|jpg|xml|ico|webmanifest)$

# Serve php scripts.
- url: /
  script: about.php
  secure: always
  redirect_http_response_code: 301

- url: /about
  script: about.php
  secure: always
  redirect_http_response_code: 301

- url: /resources
  script: viewResources.php
  secure: always
  redirect_http_response_code: 301
  
- url: /section-.*$
  script: collectResponses.php
  secure: always
  redirect_http_response_code: 301

- url: /results.*$
  script: viewResults.php
  secure: always
  redirect_http_response_code: 301

- url: /devops-maturity-csv.php
  script: devops-maturity-csv.php
  secure: always
  redirect_http_response_code: 301
